### ISSUE TITLE
Change suffix from .f95 to .f90

### ISSUE THREAD

**Issue by Beliavsky** [HamzaM3/fortran-tuto#1]
Thanks for your project. I added it to my list https://github.com/Beliavsky/Fortran-code-on-GitHub.

Please consider changing the source file suffixes from .f95 to .f90.
The .f90 suffix means that the source code is free format, not that
the code conforms to the Fortran 90 standard. Code that uses the .f90
suffix can use features from any Fortran standard. All Fortran
compilers recognize .f90 as a suffix indicating free source form, but
some may not recognize a suffix such as .f95, .f03, .f08, or .f18.
Some users may have build tools that do not recognize suffixes other
than .f90. Most Fortran source code on GitHub that uses features from
a standard more recent than Fortran 90 still uses the .f90 suffix.

**Comment by HamzaM3** [comment]
Thank you very much for your advice.

Do you have a way to contact you privately ? I have a few questions about Fortran to ask you.

**Comment by Beliavsky** [comment]
I participate in Fortran Discourse https://fortran-lang.discourse.group/. Please ask questions there.

**Comment by HamzaM3** [comment]
Okay thank you very much.
